name: food_delivery_app
description: A complete food delivery application with Flutter and Bloc
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Networking
  dio: ^5.4.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Functional Programming
  dartz: ^0.10.1

  # Network Connectivity
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2

  # UI Components & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0

  # Image Handling
  image_picker: ^1.0.7

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^2.1.1

  # Firebase (Optional - for push notifications, analytics) - Temporarily disabled
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.9
  # firebase_analytics: ^10.8.0

  # Date & Time
  intl: ^0.19.0
  timeago: ^3.6.0

  # URL Launcher
  url_launcher: ^6.2.4

  # Permissions
  permission_handler: ^11.2.0

  # Utils
  uuid: ^4.3.3
  logger: ^2.0.2+1
  path: ^1.8.3

  # Supabase Backend Integration
  supabase_flutter: ^2.3.0

  # Security & Encryption
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.6

  # Code Generation
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

